language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly
  
matrix:
    allow_failures:
        - php: nightly
  
sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.3"
  - travis_retry composer clear-cache
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --no-interaction

before_script:
  - mysql -e 'create database myapp_test;'  
  - mysql -u root myapp_test < tests/data/sql/1.0.0-luya-payment.sql
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then  PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --configuration travis.phpunit.xml
  
after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then travis_retry php vendor/bin/coveralls -v; fi
